# Generated by Django 5.0.6 on 2024-06-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1, verbose_name='레벨')),
                ('point', models.IntegerField(default=0, verbose_name='포인트')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.IntegerField(default=0, verbose_name='경험치')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('hunger_degree', models.IntegerField(default=0, verbose_name='배고픔 정도')),
                ('type', models.CharField(max_length=50, verbose_name='캐릭터 종류')),
                ('random_boxes', models.IntegerField(default=0, verbose_name='랜덤 박스 갯수')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
                ('petrating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pets.petrating', verbose_name='레이팅 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, verbose_name='아이템 이름')),
                ('image_url', models.CharField(max_length=254, verbose_name='아이템 이미지 URL')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='pets.pet', verbose_name='펫 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=254, verbose_name='배경화면')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='pets.pet', verbose_name='펫 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(verbose_name='종류')),
                ('item_name', models.CharField(max_length=10, verbose_name='아이템 이름')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='pets.pet', verbose_name='펫 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backgrounds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_lists', to='pets.background', verbose_name='Backgrounds ID')),
                ('clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_lists', to='pets.clothes', verbose_name='Clothes ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lists', to='pets.pet', verbose_name='펫 ID')),
                ('snacks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_lists', to='pets.snack', verbose_name='Snacks ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
