# Generated by Django 5.0.6 on 2024-06-04 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0, verbose_name='경험치')),
                ('level', models.IntegerField(default=1, verbose_name='레벨')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('status', models.CharField(max_length=50, verbose_name='상태')),
                ('type', models.CharField(max_length=50, verbose_name='캐릭터 종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
        ),
    ]
