version: "3"

services:
  web:
    build:
      context: .
      dockerfile: django/Dockerfile
    container_name: dg01
    command: >
      bash -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
      - /var/www/html:/var/www/html
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:12.2
    container_name: ps01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
