version: "3"

services:
  web:
    build: .
    container_name: dg01
    command: >
      bash -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static/
    depends_on:
      - web

  db:
    image: postgres:12.2
    container_name: ps01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume: